//
// Emoji Overrides - override built-in emoji symbols with custom Discord emojis.
// Each key maps an identifier used across the bot's UI to an emoji string.
// Use unicode glyphs ("🔴") or custom Discord emoji IDs ("<:name:123456789>").
//
// You only need to specify keys you want to override - everything is optional.
// All available keys (with defaults) are listed below for reference.
//

export default {
  // Success: "🟢",
  // Error: "🔴",
  // Warning: "🟡",
  // Info: "🔵",
  // Check: "✅",
  // Cross: "❌",
  // Loading: "⏳",
  // Sakura: "🌸",
  // Lemon: "🍋",
  // ArrowLeft: "⬅️",
  // ArrowRight: "➡️",
  // Pages: "📄",
  // Bullet: "⚡",
  // Bot: "🤖",
  // Terminal: "💻",
  // Gear: "⚙️",
  // Crown: "👑",
  // Lock: "🔒",
  // Unlock: "🔓",
  // Search: "🔍",
  // Feedback: "📝",
  // Star: "⭐",
  // Shield: "🛡️",
  // Bell: "🔔",
  // Fire: "🔥",
  // Afk: "💤",
  // Mail: "📬",
  // Wave: "👋",
  // Edit: "✏️",
  // Clock: "🕐",
  // WarningSign: "⚠️",
  // Guild: "🏰",
  // Admin: "🔑",
  // Analytics: "📊",
  // Cleanup: "🧹",
  // Repo: "📦",
  // Download: "📥",
  // Install: "🔧",
  // Uninstall: "🗑️",
  // Database: "🐘",
  // Cache: "🧠",
  // Gateway: "🌐",
  // Cpu: "🖥️",
  // Space: "⠀",
  // Latency: "📡",
  // Uptime: "⏱️",
  // Trade: "📊",
  // Memory: "🧠",
  // Position: "📈",
  // Servers: "🏰",
  // Members: "👥",
  // Redis: "🔴",
  // Sql: "🐘",
};
