//
// Emoji Overrides — override built-in emoji symbols with custom Discord emojis.
// Each key maps an identifier used across the bot's UI to an emoji string.
// Use unicode glyphs ("🔴") or custom Discord emoji IDs ("<:name:123456789>").
//
// You only need to specify keys you want to override — everything is optional.
// All available keys (with defaults) are listed below for reference.
//

export default {
  // SUCCESS: "🟢",
  // ERROR: "🔴",
  // WARNING: "🟡",
  // INFO: "🔵",
  // CHECK: "✅",
  // CROSS: "❌",
  // LOADING: "⏳",
  // SAKURA: "🌸",
  // LEMON: "🍋",
  // ARROW_LEFT: "⬅️",
  // ARROW_RIGHT: "➡️",
  // PAGES: "📄",
  // BULLET: "⚡",
  // BOT: "🤖",
  // TERMINAL: "💻",
  // GEAR: "⚙️",
  // CROWN: "👑",
  // LOCK: "🔒",
  // UNLOCK: "🔓",
  // SEARCH: "🔍",
  // FEEDBACK: "📝",
  // STAR: "⭐",
  // SHIELD: "🛡️",
  // BELL: "🔔",
  // FIRE: "🔥",
  // AFK: "💤",
  // MAIL: "📬",
  // WAVE: "👋",
  // EDIT: "✏️",
  // CLOCK: "🕐",
  // WARNING_SIGN: "⚠️",
  // GUILD: "🏰",
  // ADMIN: "🔑",
  // ANALYTICS: "📊",
  // CLEANUP: "🧹",
  // REPO: "📦",
  // DOWNLOAD: "📥",
  // INSTALL: "🔧",
  // UNINSTALL: "🗑️",
  // DATABASE: "🐘",
  // CACHE: "🧠",
  // QUEUE: "🐇",
  // GATEWAY: "🌐",
  // CPU: "🖥️",
  // SPACE: "⠀",
  // LATENCY: "📡",
  // UPTIME: "⏱️",
  // TRADE: "📊",
  // MEMORY: "🧠",
  // POSITION: "📈",
  // SERVERS: "🏰",
  // MEMBERS: "👥",
  // REDIS: "🔴",
  // SQL: "🐘",
  // RABBIT: "🐇",
};
