listeners.tcp.default = 5672
management.tcp.port = 15672

disk_free_limit.relative = 1.0
vm_memory_high_watermark.relative = 0.8

heartbeat = 60
connection_max = 500
channel_max = 100

collect_statistics = none
